services:
  postgres:
    build:
      context: ./internal/storage/postgres
      dockerfile: Dockerfile
    image: postgresdb:1.0  # Используем ранее созданный образ
    container_name: postgres-container
    ports:
      - "5433:5432"
    restart: always